### ISSUE TITLE
install a vim bundle

### ISSUE THREAD

**Issue by owenthereal** [owenthereal/vpm#1]
As a developer, I want to run `vbm install command-t` and it installs the latest version of the command-t vim plugin to `~/.vim`.
### Client (Bash)
- command format: `vbm <command> <plugins> [options]`
- download a plugin tar `curl http://vimbundles.org/bundles/#{name}/versions/#{version}/downloads -o ~/.vim/tmp/`
- untar it
- organize it with similar dir structure like [pathogen](http://vimcasts.org/episodes/synchronizing-plugins-with-git-submodules-and-pathogen)
### Server (Clojure?)
- GET `http://vimbundles.org/bundles/#{name}/versions/#{version}/downloads`
### Reference
- [pathogen](http://vimcasts.org/episodes/synchronizing-plugins-with-git-submodules-and-pathogen)
- [shunit2](http://code.google.com/p/shunit2/wiki/GeneralFaq)
- [bats](https://github.com/sstephenson/bats)

**Comment by MichaelBaker** [comment]
I was thinking about this and do we really need a server? If the api on http://www.vim.org/scripts/index.php is good, we might be able to query it directly and avoid having our own server.

**Comment by MichaelBaker** [comment]
Also I think it should be called the Vim Plugin Manager :^P

**Comment by owenthereal** [comment]
I am ok with Vim Plugin Manager. I got the name from Eclipse. They call a plugin bundle. Does vim.org have any API to retrieve the Vim Plugin?

**Comment by owenthereal** [comment]
Also I found the domain name `vimplugins.org` has been taken...

**Comment by MichaelBaker** [comment]
I'm not sure about vim.org's API. It's something we'll need to investigate.

These URLs are free:
http://vimpluginmanager.org/
http://vimpluginmanager.com/
http://vimpluginmanager.net/
http://vpm.net/

**Comment by owenthereal** [comment]
Maybe the first pass of the client implementation would be:
- define a manifest file (VimPlugins.yml) to declare a list of plugins to manage by VPM (parse it with `sed`):

``` ruby
plugin command-t
plugin nerd-tree
...
```
- run `vpm` to install all the plugins
- for each plugin, it uses `vpm install <plugin>`

For the first pass, maybe not implement a backend yet, use git to download the vim plugin and organized with the dir structure like pathogen. The VimPlugins.yml file may look like this:

``` ruby
plugin command-t :git => "https://github.com/wincent/Command-T.git", :tag => 1.3.1
...
```

**Comment by owenthereal** [comment]
http://vim-plugins.org is available!!

**Comment by MichaelBaker** [comment]
Ok, we might need to write a server. I don't see an API on vim.org.

**Comment by owenthereal** [comment]
TODO:
- vpm setup (Michael)
  - insert our script for setup vimrc which loads our setting before anything else
  - install pathogen when it's not there
- `vpm install --git https://github.com/wincent/Command-T.git --tag 1.3.1` (done)
  - generate an index file for installed plugins in `~/.vim/vpm/plugins`
  - the index yaml file may look like:

``` yaml
command-t:
  type: git
  remote: https://github.com/wincent/Command-T.git
  revision: 18686a82a2e4d015b877bf0b6867a269aa8a284f
nerd-tree:
  type: vp
  version: 1.2.0
```
- `vpm list`
  - run `vpm list` to show a list of installed plugins from `~/.vim/vpm/plugins`
  - the output may look like this:

``` bash
$ vpm list (Owen)
command-t nerd-tree
```
- `vpm remove`
  - remove plugin from `~/.vim/bundle`
  - update the index file
- support install script for complex plugin
  - a server to store vim plugins zip
    - vpspec
    - setup script if any
  - client download zip file, unzip it to ~/.vim/bundle
  - run setup script if any
- vpm release 
- support :tag for :git

**Comment by owenthereal** [comment]
I am thinking about it more on the way home. I think we should support `vpm remove` and `vpm install` for the ease of use. But still haven't figured out what's the best way to integrate it with the VimPlugins file. Or maybe it's not necessary.

**Comment by owenthereal** [comment]
flag close since I have created separate issues for each one
